from django.contrib import admin
from Neverwherebot.models import *

# Register your models here.
admin.site.register(Game)
admin.site.register(Player)
admin.site.register(Character)
admin.site.register(Skill)
admin.site.register(CharacterSkill)
admin.site.register(Perk)
admin.site.register(CharacterPerk)
admin.site.register(Prerequisite)
admin.site.register(Ability)
admin.site.register(Spell)
admin.site.register(College)
admin.site.register(Acre)
admin.site.register(Worksite)
admin.site.register(Application)
admin.site.register(Employee)
admin.site.register(Job)
admin.site.register(Upgrade)
admin.site.register(HerbList)
admin.site.register(ForageList)
admin.site.register(HuntingList)
admin.site.register(Prey)
admin.site.register(FishingList)
admin.site.register(BaitEffect)
admin.site.register(MiningSite)
admin.site.register(Tunnel)
admin.site.register(OreList)
admin.site.register(DisasterList)
admin.site.register(Charge)
admin.site.register(Crop)
admin.site.register(CropDescription)
admin.site.register(Ore)
admin.site.register(Disaster)
admin.site.register(Storage)
admin.site.register(Craft)
admin.site.register(Message)
admin.site.register(Process)
admin.site.register(ProcessInput)
admin.site.register(ProcessOutput)
admin.site.register(Item)
admin.site.register(ItemType)
admin.site.register(Building)
admin.site.register(Tending)